# Server
server:
  port: 8080

# PostgreSQL Config
spring:
  application:
    name: event-management
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA Config
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect